// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEjgzA4AThAUCgXqEy99Ng1AoXiLbG18M',
    appId: '1:1911779390:web:f12dffad0933e89250a16f',
    messagingSenderId: '1911779390',
    projectId: 'archef-alwafa',
    authDomain: 'archef-alwafa.firebaseapp.com',
    storageBucket: 'archef-alwafa.appspot.com',
    measurementId: 'G-CX0TJT1X80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDne1U3gVZpppndlQw3Hve-hs_BkWlVIVg',
    appId: '1:1911779390:android:954d9dcc277c747f50a16f',
    messagingSenderId: '1911779390',
    projectId: 'archef-alwafa',
    storageBucket: 'archef-alwafa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcJq_3kTMEMErh5AIw9V-EwqvbeR6Qd-o',
    appId: '1:1911779390:ios:cce5a712844bd00050a16f',
    messagingSenderId: '1911779390',
    projectId: 'archef-alwafa',
    storageBucket: 'archef-alwafa.appspot.com',
    iosClientId: '1911779390-4hsut59m9vnv0joebf9av7jlnrd74s4v.apps.googleusercontent.com',
    iosBundleId: 'com.archive.archiveAlWafa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcJq_3kTMEMErh5AIw9V-EwqvbeR6Qd-o',
    appId: '1:1911779390:ios:cce5a712844bd00050a16f',
    messagingSenderId: '1911779390',
    projectId: 'archef-alwafa',
    storageBucket: 'archef-alwafa.appspot.com',
    iosClientId: '1911779390-4hsut59m9vnv0joebf9av7jlnrd74s4v.apps.googleusercontent.com',
    iosBundleId: 'com.archive.archiveAlWafa',
  );
}
